#!/usr/bin/env python3
"""Refresh tag-index.md from the Eagle library. Run with --check to only report staleness (exit 1 if stale)."""
import json, os, sys, collections

LIB = "/Users/Kirill/Pictures/My data and visual technicks base.library"
IMAGES = os.path.join(LIB, "images")
TASTE_DIR = os.path.dirname(os.path.abspath(__file__))
STATE_PATH = os.path.join(TASTE_DIR, "state.json")
INDEX_PATH = os.path.join(TASTE_DIR, "tag-index.md")


def library_signature():
    mtime = json.load(open(os.path.join(LIB, "mtime.json")))
    return {"count": len(mtime), "max_mtime": max(mtime.values()) if mtime else 0}


def load_items():
    items = []
    for d in sorted(os.listdir(IMAGES)):
        mpath = os.path.join(IMAGES, d, "metadata.json")
        if not os.path.isfile(mpath):
            continue
        m = json.load(open(mpath))
        if m.get("isDeleted"):
            continue
        m["_dir"] = d
        items.append(m)
    return items


def regen():
    items = load_items()
    tagcount = collections.Counter()
    by_tag = collections.defaultdict(list)
    for i in items:
        for t in i.get("tags", []):
            tagcount[t.lower()] += 1
            by_tag[t.lower()].append(i)

    out = [
        "---",
        "name: taste-tag-index",
        "description: Full raw index of Kirill's Eagle reference library, grouped by tag — name + URL + Eagle item id per entry",
        "metadata:",
        "  type: reference",
        "---",
        "",
        f"Source: Eagle library `~/Pictures/My data and visual technicks base.library` (folder «Inspiration», some in «Links»). "
        f"{len(items)} active items, {len(tagcount)} unique tags. Regenerated by `regen-tag-index.py` — "
        f"run that script (or `--check`) rather than hand-editing; it's kept in sync with the live library, not a frozen snapshot.",
        "",
        "Lookup by Eagle item id: `images/<id>.info/metadata.json` in the library, thumbnail is `<id>.info/<name>_thumbnail.png`.",
        "",
        "## Tag frequency (all tags, item counts)",
        "",
        ", ".join(f"{t} ({c})" for t, c in tagcount.most_common()),
        "",
        "## Items by tag",
        "",
    ]
    for t, c in tagcount.most_common():
        out.append(f"### {t} ({c})")
        seen = set()
        for i in by_tag[t]:
            key = i["_dir"]
            if key in seen:
                continue
            seen.add(key)
            name = i["name"].strip()
            url = i.get("url", "")
            out.append(f"- {name} — {url} `[{i['_dir']}]`" if url else f"- {name} `[{i['_dir']}]`")
        out.append("")

    with open(INDEX_PATH, "w") as f:
        f.write("\n".join(out))

    sig = library_signature()
    sig["item_count_active"] = len(items)
    json.dump(sig, open(STATE_PATH, "w"), indent=2)
    return sig


def is_stale():
    if not os.path.isfile(STATE_PATH):
        return True
    state = json.load(open(STATE_PATH))
    sig = library_signature()
    return state.get("count") != sig["count"] or state.get("max_mtime") != sig["max_mtime"]


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(1 if is_stale() else 0)
    sig = regen()
    print(f"regenerated tag-index.md — {sig['item_count_active']} active items, signature {sig}")
